# Generated by Django 5.0.6 on 2024-05-10 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_start', models.DateField()),
                ('age_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_start', models.DecimalField(decimal_places=3, max_digits=6)),
                ('weight_end', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='<django.db.models.fields.related.ForeignKey><django.db.models.fields.related.ForeignKey>', max_length=255, unique=True)),
                ('id_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppArena.age')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status_application', models.BooleanField(default=False)),
                ('id_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_applications', to=settings.AUTH_USER_MODEL)),
                ('id_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_applications', to=settings.AUTH_USER_MODEL)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppArena.category')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_competition', models.CharField(max_length=45, verbose_name='Название')),
                ('date_event', models.DateField(verbose_name='Дата проведения')),
                ('address', models.CharField(max_length=127, verbose_name='Адрес')),
                ('status_competition', models.BooleanField(default=True, verbose_name='Статус')),
                ('slug', models.SlugField(default='<django.db.models.fields.CharField>', max_length=255, unique=True, verbose_name='Уникальное название')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='id_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppArena.competition'),
        ),
        migrations.CreateModel(
            name='ExpansionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=45, verbose_name='Отчество')),
                ('category_referee', models.IntegerField(blank=True, null=True, verbose_name='Катеория')),
                ('license_number_trainer', models.CharField(blank=True, max_length=10, null=True, verbose_name='Лицензия')),
                ('medical_insurance_participants', models.CharField(blank=True, max_length=10, null=True, verbose_name='Страховка')),
                ('weight_participants', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Вес')),
                ('date_birth_participants', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('assessments', models.JSONField(blank=True, null=True)),
                ('result', models.BooleanField(blank=True, null=True)),
                ('id_blue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_meets', to=settings.AUTH_USER_MODEL)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppArena.category')),
                ('id_judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_meets', to=settings.AUTH_USER_MODEL)),
                ('id_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_meets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='id_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppArena.weight'),
        ),
    ]
