# Generated by Django 5.0.6 on 2024-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArena', '0002_alter_competition_name_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='date_end',
            field=models.DateField(default='2024-05-03', verbose_name='Дата завершения'),
        ),
    ]
