# Generated by Django 5.0.6 on 2024-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArena', '0003_competition_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_end',
            field=models.DateField(verbose_name='Дата завершения'),
        ),
    ]
