# Generated by Django 5.0.6 on 2024-05-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArena', '0004_alter_competition_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansionuser',
            name='medical_insurance_participants',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер страхования жизни'),
        ),
    ]
