# Generated by Django 5.0.6 on 2024-05-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppArena', '0007_alter_competition_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
