# Generated by Django 5.0.6 on 2024-05-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppArena', '0008_remove_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='id_participant',
            new_name='participant',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='id_trainer',
            new_name='trainer',
        ),
    ]
