# Generated by Django 5.0.6 on 2024-05-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArena', '0011_alter_expansionuser_category_referee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='assessments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
