# Generated by Django 5.0.6 on 2024-06-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArena', '0012_alter_meet_assessments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='id_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_meets', to='AppArena.expansionuser'),
        ),
    ]
