# Generated by Django 5.0.6 on 2024-06-02 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArena', '0013_alter_meet_id_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppArena.expansionuser'),
        ),
    ]
