# Generated by Django 5.0.6 on 2024-06-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArena', '0016_alter_meet_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
